blank_issues_enabled: false
contact_links:
  - name: OpenXR Toolkit Homepage
    url: https://mbucchia.github.io/OpenXR-Toolkit/
    about: The homepage has A LOT OF INFORMATION. Check there first for the answer to your questions/issues. There is a Search bar at the top.
  - name: OpenXR Toolkit Discord (NO OPENCOMPOSITE SUPPORT)
    url: https://discord.gg/mPKJYeGUjH
    about: If you have checked all the information above, but still cannot address your questions/issues, ask and answer questions on our Discord.
